#!/bin/bash -x

#example on Debian GNU/Linux 10 (buster) cluster

###
# add the following to your .bashrc
###

#MYROOT is local root location
export MYROOT=/home/mzimmer/home_ftalc/root
export PKG_CONFIG_PATH=$MYROOT/usr/lib/x86_64-linux-gnu/pkgconfig/:$MYROOT/usr/share/pkgconfig
export PATH=$MYROOT/bin:$MYROOT/usr/bin:$PATH
export LD_LIBRARY_PATH=$MYROOT/usr/lib/:$MYROOT/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$MYROOT/usr/

#you may need to compile or locally install those yourself
module load boost/1.69.0_gcc-6.4.0 cmake/3.13.4_gcc-6.4.0 openblas/0.3.5_gcc-6.4.0 intel-tbb/2019.2_gcc-6.4.0

#exit .bashrc

###
# install package locally
###

#store .deb files
mkdir -p $MYROOT/deb
cd $MYROOT/deb
#download package
apt-get download libgflags-dev libgoogle-glog-dev libprotobuf-dev protobuf-compiler xmlstarlet libprotobuf17 liblmdb-dev libleveldb-dev libsnappy-dev libprotoc17 libgoogle-glog0v5 libgflags2.2 libleveldb1d libgtest-dev
#locally install them
find . -name '*.deb' | xargs -I % dpkg -X % $MYROOT/
#fix links and config, may display errors, it's fine
find $MYROOT/usr/lib/x86_64-linux-gnu/pkgconfig/ -type f -name '*.pc' | xargs sed -i 's|^prefix=.*$|prefix='$MYROOT'/usr|'
find $MYROOT/usr/lib/x86_64-linux-gnu/pkgconfig/ -type f -name '*.pc' | xargs sed -i 's|^libdir=.*$|libdir='$MYROOT'/usr/lib/x86_64-linux-gnu|'
find $MYROOT/usr/share/pkgconfig -type f -name '*.pc' | xargs sed -i 's|^prefix=.*$|prefix='$MYROOT'/usr|'
find $MYROOT/usr/share/pkgconfig -type f -name '*.pc' | xargs sed -i 's|^libdir=.*$|libdir='$MYROOT'/usr/lib/x86_64-linux-gnu|'
find $MYROOT -xtype l -name '*.so' | xargs -I % -n 1 bash -c 'link_name=$(basename $(readlink -f %)) ; if [ -e /usr/lib/x86_64-linux-gnu/$link_name ] ; then rm % ; ln -s /usr/lib/x86_64-linux-gnu/$link_name % ; echo fixing % to /usr/lib/x86_64-linux-gnu/$link_name ; fi'

cd $MYROOT/usr/bin
ln -s xmlstarlet xml

###
# needed compilation
###
mkdir -p $MYROOT/compiled

#gtest
cd $MYROOT/compiled
mkdir gtest
cp -r $MYROOT/usr/src/gtest/* gtest
cd gtest
CXXFLAGS="-I $MYROOT/usr/include" cmake .
make -j4
cp libgtest* $MYROOT/usr/lib/

#caffe
cd $MYROOT/compiled
git clone https://github.com/matthieu637/caffe.git
cd caffe
mkdir build
cd build
cmake ../ -DBLAS=Open -DBUILD_python=OFF -DUSE_OPENCV=OFF -DCPU_ONLY=On -DCMAKE_INSTALL_PREFIX:PATH=$MYROOT/usr
make -j4
make install

#build ddrl later
